[package]
name = "crypto_prices"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ureq = "2.9.6"
serde_json ="1.0.113"
serde = { version = "1.0", features = ["derive"] }